// Mock Data for QMS Demo Mode
import type { Profile, Organization, Document, Capa, NonConformance, BatchRecord, BatchStep, Supplier, FormTemplate, FormInstance, AuditTrail, Audit, Training, Risk, DocumentPrerequisite, OrganizationMember, ChangeControl, Deviation } from '@/types/qms';

// ============================================================================
// Profiles
// ============================================================================

export const mockProfiles: Profile[] = [
  {
    id: 'user-001',
    email: 'admin@qms-demo.com',
    fullName: 'Marie Dupont',
    role: 'admin',
    department: 'Quality Assurance',
    jobTitle: 'QA Director',
    phone: '+33 1 23 45 67 89',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user-002',
    email: 'qm@qms-demo.com',
    fullName: 'Jean Martin',
    role: 'quality_manager',
    department: 'Quality Assurance',
    jobTitle: 'Quality Manager',
    phone: '+33 1 23 45 67 90',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user-003',
    email: 'auditor@qms-demo.com',
    fullName: 'Sophie Laurent',
    role: 'auditor',
    department: 'Internal Audit',
    jobTitle: 'Lead Auditor',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user-004',
    email: 'dc@qms-demo.com',
    fullName: 'Pierre Bernard',
    role: 'document_controller',
    department: 'Document Control',
    jobTitle: 'Document Control Specialist',
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user-005',
    email: 'exec@qms-demo.com',
    fullName: 'Claire Moreau',
    role: 'executive',
    department: 'Executive',
    jobTitle: 'VP Quality',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'user-006',
    email: 'operator@qms-demo.com',
    fullName: 'Lucas Petit',
    role: 'operator',
    department: 'Production',
    jobTitle: 'Manufacturing Operator',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
];

// ============================================================================
// Organizations
// ============================================================================

export const mockOrganizations: Organization[] = [
  {
    id: 'org-001',
    name: 'PharmaQMS Demo',
    slug: 'pharmaqms-demo',
    subscriptionStatus: 'active',
    settings: JSON.stringify({
      setup_completed: true,
      industry_type: 'medical_device',
      applicable_standards: ['ISO 13485:2016', 'ISO 14971:2019', 'FDA 21 CFR 820'],
      active_modules: ['documents', 'capa', 'ncr', 'audits', 'training', 'reports', 'compliance', 'risks', 'hierarchy', 'batch_records', 'suppliers', 'forms', 'change_control', 'deviations', 'oos_oot'],
      company_name: 'PharmaQMS Demo',
      require_electronic_signatures: true,
      require_prerequisite_docs: true,
      audit_trail_enabled: true,
      notification_settings: {
        capa_overdue: true,
        ncr_overdue: true,
        document_expiry: true,
        training_overdue: true,
        audit_due: true,
      },
    }),
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
];

// ============================================================================
// Organization Members
// ============================================================================

export const mockOrgMembers: OrganizationMember[] = [
  { id: 'mem-001', organizationId: 'org-001', userId: 'user-001', role: 'owner', status: 'active', createdAt: '2024-01-15T08:00:00Z' },
  { id: 'mem-002', organizationId: 'org-001', userId: 'user-002', role: 'admin', status: 'active', createdAt: '2024-01-20T09:00:00Z' },
  { id: 'mem-003', organizationId: 'org-001', userId: 'user-003', role: 'member', status: 'active', createdAt: '2024-02-01T09:00:00Z' },
  { id: 'mem-004', organizationId: 'org-001', userId: 'user-004', role: 'member', status: 'active', createdAt: '2024-02-15T09:00:00Z' },
  { id: 'mem-005', organizationId: 'org-001', userId: 'user-005', role: 'member', status: 'active', createdAt: '2024-01-15T09:00:00Z' },
  { id: 'mem-006', organizationId: 'org-001', userId: 'user-006', role: 'member', status: 'active', createdAt: '2024-03-01T09:00:00Z' },
];

// ============================================================================
// Documents
// ============================================================================

export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    documentNumber: 'SOP-QMS-001',
    title: 'Document Control Procedure',
    type: 'SOP',
    version: '3.0',
    status: 'Approved',
    effectiveDate: '2024-01-15T00:00:00Z',
    nextReview: '2025-01-15T00:00:00Z',
    owner: 'Pierre Bernard',
    department: 'Document Control',
    description: 'Defines the procedure for creating, reviewing, approving, and controlling documents within the QMS.',
    classification: 'Internal',
    retentionPeriod: '10 years',
    documentLevel: 2,
    code: 'PR-4.2.3',
    isoClause: '§4.2.3',
    triggers: ['SOP-QMS-002', 'SOP-QMS-003'],
    reviewCycleMonths: 24,
    authorId: 'user-004',
    organizationId: 'org-001',
    createdById: 'user-004',
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'doc-002',
    documentNumber: 'SOP-QMS-002',
    title: 'CAPA Management Procedure',
    type: 'SOP',
    version: '2.1',
    status: 'Approved',
    effectiveDate: '2024-02-01T00:00:00Z',
    nextReview: '2025-02-01T00:00:00Z',
    owner: 'Jean Martin',
    department: 'Quality Assurance',
    description: 'Defines the procedure for initiating, investigating, and closing Corrective and Preventive Actions.',
    classification: 'Internal',
    retentionPeriod: '15 years',
    documentLevel: 2,
    code: 'PR-8.5.2',
    isoClause: '§8.5.2',
    triggers: ['SOP-QMS-003'],
    reviewCycleMonths: 24,
    authorId: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2023-07-01T08:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'doc-003',
    documentNumber: 'SOP-QMS-003',
    title: 'Non-Conformance Management',
    type: 'SOP',
    version: '2.0',
    status: 'Approved',
    effectiveDate: '2024-01-20T00:00:00Z',
    nextReview: '2025-01-20T00:00:00Z',
    owner: 'Jean Martin',
    department: 'Quality Assurance',
    description: 'Procedure for identifying, documenting, and resolving non-conformances.',
    classification: 'Internal',
    retentionPeriod: '15 years',
    documentLevel: 2,
    code: 'PR-8.7',
    isoClause: '§8.7',
    triggers: ['SOP-QMS-002'],
    reviewCycleMonths: 24,
    authorId: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2023-08-01T08:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'doc-004',
    documentNumber: 'SOP-PROD-001',
    title: 'Sterile Manufacturing Process',
    type: 'SOP',
    version: '4.2',
    status: 'Approved',
    effectiveDate: '2024-03-01T00:00:00Z',
    nextReview: '2025-03-01T00:00:00Z',
    owner: 'Lucas Petit',
    department: 'Production',
    description: 'Standard operating procedure for sterile manufacturing of pharmaceutical products.',
    classification: 'Confidential',
    retentionPeriod: '20 years',
    documentLevel: 2,
    code: 'WI-PROD-001',
    isoClause: '§8.1',
    triggers: ['SOP-PROD-001'],
    reviewCycleMonths: 36,
    authorId: 'user-006',
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2022-01-15T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'doc-005',
    documentNumber: 'POL-QMS-001',
    title: 'Quality Policy',
    type: 'Policy',
    version: '1.0',
    status: 'Approved',
    effectiveDate: '2024-01-15T00:00:00Z',
    nextReview: '2027-01-15T00:00:00Z',
    owner: 'Claire Moreau',
    department: 'Executive',
    description: 'Company quality policy statement and commitment to regulatory compliance.',
    classification: 'Internal',
    retentionPeriod: 'Permanent',
    documentLevel: 1,
    code: 'POL-001',
    isoClause: '§5.2',
    triggers: [],
    reviewCycleMonths: 36,
    authorId: 'user-005',
    organizationId: 'org-001',
    createdById: 'user-005',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'doc-006',
    documentNumber: 'WI-PROD-001',
    title: 'Cleanroom Entry Procedure',
    type: 'WI',
    version: '2.0',
    status: 'Under Review',
    owner: 'Lucas Petit',
    department: 'Production',
    description: 'Work instruction for entering and exiting the cleanroom environment.',
    classification: 'Internal',
    retentionPeriod: '10 years',
    documentLevel: 3,
    code: 'WI-PROD-002',
    isoClause: '§8.1',
    triggers: ['SOP-PROD-001'],
    reviewCycleMonths: 24,
    parentDocumentId: 'doc-004',
    authorId: 'user-006',
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2023-05-01T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
  },
  {
    id: 'doc-007',
    documentNumber: 'SOP-QMS-004',
    title: 'Internal Audit Procedure',
    type: 'SOP',
    version: '1.2',
    status: 'Approved',
    effectiveDate: '2024-04-01T00:00:00Z',
    nextReview: '2025-04-01T00:00:00Z',
    owner: 'Sophie Laurent',
    department: 'Internal Audit',
    description: 'Procedure for planning, conducting, and following up on internal quality audits.',
    classification: 'Internal',
    retentionPeriod: '15 years',
    documentLevel: 2,
    code: 'PR-9.2',
    isoClause: '§9.2',
    triggers: [],
    reviewCycleMonths: 24,
    authorId: 'user-003',
    organizationId: 'org-001',
    createdById: 'user-003',
    createdAt: '2023-09-01T08:00:00Z',
    updatedAt: '2024-04-01T10:00:00Z',
  },
  {
    id: 'doc-008',
    documentNumber: 'VAL-PROD-001',
    title: 'Sterilization Process Validation - IQ',
    type: 'Validation Protocol',
    version: '1.0',
    status: 'Approved',
    effectiveDate: '2024-02-15T00:00:00Z',
    owner: 'Jean Martin',
    department: 'Quality Assurance',
    description: 'Installation Qualification protocol for the autoclave sterilization process.',
    classification: 'Confidential',
    retentionPeriod: 'Permanent',
    code: 'VAL-001',
    isoClause: '§7.5.6',
    triggers: ['SOP-PROD-001'],
    reviewCycleMonths: 48,
    validationPhase: 'IQ',
    authorId: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: 'doc-009',
    documentNumber: 'SPEC-QC-001',
    title: 'Raw Material Specification - API X-200',
    type: 'Specification',
    version: '2.0',
    status: 'Approved',
    effectiveDate: '2024-01-10T00:00:00Z',
    owner: 'Jean Martin',
    department: 'Quality Control',
    description: 'Raw material specification for Active Pharmaceutical Ingredient X-200.',
    classification: 'Confidential',
    retentionPeriod: '15 years',
    code: 'SPEC-001',
    isoClause: '§7.4',
    triggers: ['SOP-PROD-001'],
    reviewCycleMonths: 24,
    authorId: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2023-03-01T08:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'doc-010',
    documentNumber: 'RA-QMS-001',
    title: 'Product Risk Analysis - Device Alpha',
    type: 'Risk Analysis',
    version: '1.0',
    status: 'Draft',
    owner: 'Jean Martin',
    department: 'Quality Assurance',
    description: 'Risk analysis for medical device Alpha according to ISO 14971:2019.',
    classification: 'Confidential',
    retentionPeriod: 'Permanent',
    code: 'RA-001',
    isoClause: '§6.1',
    triggers: [],
    reviewCycleMonths: 24,
    authorId: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
  },
];

// ============================================================================
// CAPAs
// ============================================================================

export const mockCapas: Capa[] = [
  {
    id: 'capa-001',
    capaNumber: 'CAPA-2024-001',
    title: 'Environmental Monitoring Excursion - Cleanroom Grade A',
    type: 'Corrective',
    status: 'Implementation',
    priority: 'Critical',
    source: 'Non-Conformance',
    sourceReferenceId: 'ncr-001',
    description: 'CFU counts exceeded alert limits in Grade A cleanroom during routine environmental monitoring on 2024-03-15.',
    problemStatement: 'Environmental monitoring results showed CFU counts of 3 in Grade A area, exceeding the alert limit of 1 CFU.',
    investigationDetails: 'Investigation revealed HVAC filter degradation and improper gowning procedure adherence.',
    rootCauseAnalysis: 'The primary HEPA filter had reached end of service life and was not replaced per schedule.',
    rootCauseCategory: 'Machine',
    fiveWhys: ['CFU counts exceeded in Grade A', 'HEPA filter degraded', 'Filter not replaced on schedule', 'PM schedule not updated after filter life assessment', 'Change control for filter replacement not implemented'],
    correctiveAction: 'Replace HEPA filter immediately. Update PM schedule. Retrain personnel on gowning.',
    effectivenessVerificationMethod: 'Environmental monitoring trending for 3 consecutive months post-implementation',
    effectivenessCriteria: 'Zero excursions above alert limits for 3 consecutive months',
    effectivenessResult: 'Pending Review',
    assignedTo: 'user-002',
    dueDate: '2024-06-15T00:00:00Z',
    createdDate: '2024-03-16T08:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    linkedNcrIds: ['ncr-001'],
    createdAt: '2024-03-16T08:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'capa-002',
    capaNumber: 'CAPA-2024-002',
    title: 'Documentation Gap in Batch Record Review',
    type: 'Corrective',
    status: 'Investigation',
    priority: 'High',
    source: 'Audit Finding',
    sourceReferenceId: 'audit-001',
    linkedAuditIds: ['audit-001'],
    description: 'Internal audit found missing QA review signatures on 3 batch records for Lot BN-2024-045.',
    problemStatement: 'Batch records released without proper QA review and sign-off.',
    investigationDetails: 'Review of batch record workflow indicates QA review step was bypassed in the electronic system.',
    rootCauseAnalysis: 'System configuration allowed batch release without mandatory QA signature.',
    rootCauseCategory: 'Method',
    assignedTo: 'user-004',
    dueDate: '2024-07-01T00:00:00Z',
    createdDate: '2024-04-10T08:00:00Z',
    createdById: 'user-003',
    organizationId: 'org-001',
    createdAt: '2024-04-10T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
  },
  {
    id: 'capa-003',
    capaNumber: 'CAPA-2024-003',
    title: 'Preventive Maintenance Schedule Compliance',
    type: 'Preventive',
    status: 'Open',
    priority: 'Medium',
    source: 'Management Review',
    description: 'Trend analysis shows 15% of preventive maintenance tasks completed late in Q1 2024.',
    assignedTo: 'user-002',
    dueDate: '2024-08-01T00:00:00Z',
    createdDate: '2024-05-01T08:00:00Z',
    createdById: 'user-005',
    organizationId: 'org-001',
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z',
  },
  {
    id: 'capa-004',
    capaNumber: 'CAPA-2024-004',
    title: 'Supplier Qualification Gap - Raw Material Vendor',
    type: 'Preventive',
    status: 'Closed',
    priority: 'High',
    source: 'Supplier Issue',
    description: 'New raw material supplier was used before completing full qualification process.',
    correctiveAction: 'Implemented supplier qualification checklist with mandatory approval gates.',
    effectivenessVerificationMethod: 'Audit of all new supplier qualifications in past 12 months',
    effectivenessResult: 'Effective',
    assignedTo: 'user-002',
    dueDate: '2024-04-01T00:00:00Z',
    createdDate: '2024-01-15T08:00:00Z',
    closedDate: '2024-03-28T10:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-03-28T10:00:00Z',
  },
  {
    id: 'capa-005',
    capaNumber: 'CAPA-2024-005',
    title: 'Customer Complaint - Device Labeling Error',
    type: 'Corrective',
    status: 'Effectiveness Check',
    priority: 'Critical',
    source: 'Customer Complaint',
    description: 'Customer reported incorrect expiry date printed on Device Alpha lot BN-2024-052.',
    problemStatement: 'Device labeling contained incorrect expiry date (2026 instead of 2025).',
    rootCauseAnalysis: 'Label template in printing system was not updated after shelf-life change.',
    rootCauseCategory: 'Method',
    correctiveAction: 'Updated label template. Added verification step in label approval process.',
    effectivenessVerificationMethod: 'Review of 10 consecutive batch label approvals',
    effectivenessCriteria: 'Zero labeling errors for 10 consecutive batches',
    effectivenessResult: 'Pending Review',
    assignedTo: 'user-004',
    dueDate: '2024-05-30T00:00:00Z',
    createdDate: '2024-02-20T08:00:00Z',
    createdById: 'user-001',
    organizationId: 'org-001',
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
  },
];

// ============================================================================
// Non-Conformances
// ============================================================================

export const mockNCRs: NonConformance[] = [
  {
    id: 'ncr-001',
    ncrNumber: 'NCR-2024-001',
    title: 'Environmental Monitoring Excursion - Grade A',
    type: 'Process',
    status: 'Under Investigation',
    severity: 'Critical',
    source: 'Environmental Monitoring',
    description: 'CFU counts exceeded alert limits in Grade A cleanroom during routine monitoring.',
    lotNumber: 'BN-2024-038',
    quantityAffected: 500,
    disposition: 'Pending',
    linkedCapaId: 'capa-001',
    linkedCapaIds: ['capa-001'],
    linkedProcedureRef: 'SOP-PROD-001',
    assignedTo: 'user-002',
    createdDate: '2024-03-15T08:00:00Z',
    createdById: 'user-006',
    organizationId: 'org-001',
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
    isOosOot: false,
    phase2Required: false,
    rejectLot: false,
  },
  {
    id: 'ncr-002',
    ncrNumber: 'NCR-2024-002',
    title: 'Out of Specification Result - API Assay',
    type: 'OOS',
    status: 'Pending Disposition',
    severity: 'Major',
    source: 'Quality Control Testing',
    description: 'Assay result for API X-200 in finished product showed 92.3% vs specification 95.0-105.0%.',
    lotNumber: 'BN-2024-042',
    quantityAffected: 1000,
    disposition: 'Pending',
    isOosOot: true,
    templateId: 'ft-011',
    analyticalMethod: 'HPLC Method QC-M-001',
    measuredValue: 92.3,
    measuredUnit: '%',
    specLimit: '95.0-105.0%',
    phase1Conclusion: 'No Error Found',
    phase2Required: true,
    phase2Conclusion: 'Confirmed OOS',
    rejectLot: true,
    assignedTo: 'user-002',
    createdDate: '2024-04-05T08:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    createdAt: '2024-04-05T08:00:00Z',
    updatedAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'ncr-003',
    ncrNumber: 'NCR-2024-003',
    title: 'Packaging Defect - Seal Integrity',
    type: 'Product',
    status: 'Open',
    severity: 'Minor',
    source: 'In-Process Inspection',
    description: 'Routine in-process inspection identified 3 units with incomplete seal on blister pack.',
    lotNumber: 'BN-2024-050',
    quantityAffected: 3,
    disposition: 'Scrap',
    assignedTo: 'user-006',
    createdDate: '2024-05-12T08:00:00Z',
    createdById: 'user-006',
    organizationId: 'org-001',
    createdAt: '2024-05-12T08:00:00Z',
    updatedAt: '2024-05-12T08:00:00Z',
    isOosOot: false,
    phase2Required: false,
    rejectLot: false,
  },
  {
    id: 'ncr-004',
    ncrNumber: 'NCR-2024-004',
    title: 'Supplier Non-Conformance - Raw Material Particle Count',
    type: 'Supplier',
    status: 'Closed',
    severity: 'Major',
    source: 'Incoming Inspection',
    description: 'Incoming inspection of raw material lot RM-2024-110 from supplier MED-SUP-001 showed elevated particle counts.',
    lotNumber: 'RM-2024-110',
    quantityAffected: 50,
    disposition: 'Return to Supplier',
    supplierId: 'sup-001',
    linkedCapaId: 'capa-004',
    linkedCapaIds: ['capa-004'],
    assignedTo: 'user-002',
    createdDate: '2024-01-20T08:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    isOosOot: false,
    phase2Required: false,
    rejectLot: false,
  },
  {
    id: 'ncr-005',
    ncrNumber: 'NCR-2024-005',
    title: 'Out of Trend - Stability Study API Assay Drift',
    type: 'OOT',
    status: 'Under Investigation',
    severity: 'Major',
    source: 'Stability Study',
    description: 'Stability study for Product Alpha lot BN-2024-012 shows a trend drift in API assay results at 12-month timepoint. Results trending downward toward specification limit (95.0%) with latest result at 96.1%.',
    lotNumber: 'BN-2024-012',
    quantityAffected: 2000,
    disposition: 'Pending',
    isOosOot: true,
    analyticalMethod: 'HPLC Method QC-M-001',
    measuredValue: 96.1,
    measuredUnit: '%',
    specLimit: '95.0-105.0%',
    phase1Conclusion: 'No Error Found',
    phase2Required: true,
    phase2Conclusion: 'Pending',
    rejectLot: false,
    assignedTo: 'user-002',
    createdDate: '2024-05-20T08:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    createdAt: '2024-05-20T08:00:00Z',
    updatedAt: '2024-05-25T10:00:00Z',
  },
];

// ============================================================================
// Batch Records
// ============================================================================

export const mockBatchSteps: BatchStep[] = [
  { id: 'step-001', batchRecordId: 'batch-001', stepOrder: 1, stepName: 'Material Weighing', instructions: 'Weigh API X-200 according to master formula', expectedValue: '250.0 ± 2.5 kg', actualValue: '251.2 kg', status: 'Completed', stepType: 'Weighing', operatorId: 'user-006', performedAt: '2024-05-01T08:30:00Z', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'step-002', batchRecordId: 'batch-001', stepOrder: 2, stepName: 'Mixing', instructions: 'Mix for 30 minutes at 200 RPM', expectedValue: '30 min, 200 RPM', actualValue: '30 min, 198 RPM', status: 'Completed', stepType: 'Mixing', operatorId: 'user-006', performedAt: '2024-05-01T09:15:00Z', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'step-003', batchRecordId: 'batch-001', stepOrder: 3, stepName: 'In-Process Testing', instructions: 'Sample and test pH, viscosity, appearance', expectedValue: 'pH 6.5-7.5, Viscosity < 500 cP', status: 'Completed', stepType: 'QC Testing', operatorId: 'user-006', performedAt: '2024-05-01T10:00:00Z', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'step-004', batchRecordId: 'batch-001', stepOrder: 4, stepName: 'Filling', instructions: 'Fill 10ml vials to 10.0 ± 0.2 ml', expectedValue: '10.0 ± 0.2 ml', status: 'In Progress', stepType: 'Filling', operatorId: 'user-006', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'step-005', batchRecordId: 'batch-001', stepOrder: 5, stepName: 'Sterilization', instructions: 'Autoclave at 121°C for 15 minutes', expectedValue: '121°C, 15 min', status: 'Pending', stepType: 'Other', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'step-006', batchRecordId: 'batch-001', stepOrder: 6, stepName: 'Visual Inspection', instructions: '100% visual inspection of filled vials', expectedValue: '0 critical defects', status: 'Pending', stepType: 'Inspection', createdAt: '2024-05-01T08:00:00Z' },
];

export const mockBatchRecords: BatchRecord[] = [
  {
    id: 'batch-001',
    lotNumber: 'BN-2024-055',
    productName: 'Sterile Solution Alpha',
    productCode: 'PROD-ALPHA-001',
    batchSize: 5000,
    batchSizeUnit: 'vials',
    sopReference: 'SOP-MFG-001',
    manufacturingDate: '2024-05-01T08:00:00Z',
    expiryDate: '2026-05-01T00:00:00Z',
    status: 'In Progress',
    isLocked: false,
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2024-05-01T08:00:00Z',
    steps: mockBatchSteps,
    rawMaterials: [
      { id: 'rm-001', material: 'API X-200', lotNumber: 'API-2024-0451', supplier: 'MedPharm Raw Materials GmbH', status: 'Verified' },
      { id: 'rm-002', material: 'Sodium Chloride USP', lotNumber: 'NaCl-2024-0892', supplier: 'MedPharm Raw Materials GmbH', status: 'Verified' },
      { id: 'rm-003', material: 'Water for Injection', lotNumber: 'WFI-2024-3301', supplier: 'In-house Production', status: 'Verified' },
      { id: 'rm-004', material: '10ml Type I Borosilicate Vials', lotNumber: 'VIAL-2024-1205', supplier: 'PharmaPack Solutions SA', status: 'Pending' },
    ],
  },
  {
    id: 'batch-002',
    lotNumber: 'BN-2024-052',
    productName: 'Device Alpha',
    productCode: 'PROD-DEV-001',
    batchSize: 2000,
    batchSizeUnit: 'units',
    sopReference: 'SOP-MFG-002',
    manufacturingDate: '2024-04-15T08:00:00Z',
    expiryDate: '2025-04-15T00:00:00Z',
    status: 'Released',
    isLocked: true,
    qaReleaseDate: '2024-04-20T14:00:00Z',
    qaReleasedById: 'user-002',
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2024-04-15T08:00:00Z',
    rawMaterials: [
      { id: 'rm-005', material: 'Stainless Steel Housing', lotNumber: 'SSH-2024-0334', supplier: 'CleanTech Equipment Inc.', status: 'Verified' },
      { id: 'rm-006', material: 'Silicone Gasket', lotNumber: 'SG-2024-0712', supplier: 'MedPharm Raw Materials GmbH', status: 'Verified' },
    ],
  },
  {
    id: 'batch-003',
    lotNumber: 'BN-2024-042',
    productName: 'Sterile Solution Beta',
    productCode: 'PROD-BETA-001',
    batchSize: 10000,
    batchSizeUnit: 'vials',
    sopReference: 'SOP-MFG-003',
    manufacturingDate: '2024-03-20T08:00:00Z',
    expiryDate: '2026-03-20T00:00:00Z',
    status: 'Quarantine',
    isLocked: true,
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2024-03-20T08:00:00Z',
    rawMaterials: [
      { id: 'rm-007', material: 'API Y-500', lotNumber: 'API-2024-0223', supplier: 'MedPharm Raw Materials GmbH', status: 'Rejected' },
      { id: 'rm-008', material: 'Lactose Monohydrate', lotNumber: 'LM-2024-0561', supplier: 'MedPharm Raw Materials GmbH', status: 'Verified' },
      { id: 'rm-009', material: '5ml Type I Borosilicate Vials', lotNumber: 'VIAL-2024-0987', supplier: 'PharmaPack Solutions SA', status: 'Pending' },
    ],
  },
];

// ============================================================================
// Suppliers
// ============================================================================

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    supplierCode: 'MED-SUP-001',
    name: 'MedPharm Raw Materials GmbH',
    category: 'Raw Material',
    status: 'Qualified',
    qualificationDate: '2023-06-15T00:00:00Z',
    nextReviewDate: '2025-06-15T00:00:00Z',
    certifications: ['ISO 9001:2015', 'ISO 13485:2016', 'GMP Certificate'],
    performanceScore: 92,
    website: 'https://www.medpharm-gmbh.de',
    primaryContactName: 'Dr. Hans Mueller',
    primaryContactEmail: 'h.mueller@medpharm-gmbh.de',
    primaryContactPhone: '+49 89 1234567',
    street: 'Industriestr. 42',
    city: 'Munich',
    stateProvince: 'Bavaria',
    postalCode: '80339',
    country: 'Germany',
    emergencyContactName: 'Klaus Weber',
    emergencyContactPhone: '+49 89 7654321',
    qualificationMethod: 'On-Site Audit',
    qualificationDocRef: 'QA-AUD-2023-004',
    linkedDocumentIds: ['doc-009'],
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2023-06-15T08:00:00Z',
  },
  {
    id: 'sup-002',
    supplierCode: 'PKG-SUP-001',
    name: 'PharmaPack Solutions SA',
    category: 'Packaging',
    status: 'Qualified',
    qualificationDate: '2023-08-01T00:00:00Z',
    nextReviewDate: '2025-08-01T00:00:00Z',
    certifications: ['ISO 9001:2015', 'ISO 15378'],
    performanceScore: 88,
    website: 'https://www.pharmapack-sa.ch',
    primaryContactName: 'Marie Dupont',
    primaryContactEmail: 'm.dupont@pharmapack-sa.ch',
    primaryContactPhone: '+41 22 9876543',
    street: 'Route de la Gare 15',
    city: 'Geneva',
    stateProvince: 'Geneva',
    postalCode: '1201',
    country: 'Switzerland',
    emergencyContactName: 'Pierre Martin',
    emergencyContactPhone: '+41 22 1234567',
    qualificationMethod: 'Certificate Review',
    qualificationDocRef: 'QA-CERT-2023-012',
    linkedDocumentIds: ['doc-001'],
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2023-08-01T08:00:00Z',
  },
  {
    id: 'sup-003',
    supplierCode: 'EQUIP-001',
    name: 'CleanTech Equipment Inc.',
    category: 'Equipment',
    status: 'Conditional',
    qualificationDate: '2024-01-10T00:00:00Z',
    nextReviewDate: '2024-07-10T00:00:00Z',
    certifications: ['ISO 9001:2015', 'CE Marking'],
    performanceScore: 75,
    website: 'https://www.cleantechequip.com',
    primaryContactName: 'Sarah Johnson',
    primaryContactEmail: 's.johnson@cleantechequip.com',
    primaryContactPhone: '+1 508 5551234',
    street: '200 Technology Park Dr',
    city: 'Worcester',
    stateProvince: 'MA',
    postalCode: '01605',
    country: 'United States',
    emergencyContactName: 'Tom Baker',
    emergencyContactPhone: '+1 508 5559999',
    qualificationMethod: 'Questionnaire',
    qualificationDocRef: 'QA-QUES-2024-002',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'sup-004',
    supplierCode: 'LAB-001',
    name: 'Analytix Laboratory Services',
    category: 'Laboratory',
    status: 'Under Evaluation',
    certifications: ['ISO 17025', 'GLP Certificate'],
    performanceScore: 0,
    website: 'https://www.analytix-lab.co.uk',
    primaryContactName: 'Dr. Emma Clark',
    primaryContactEmail: 'e.clark@analytix-lab.co.uk',
    primaryContactPhone: '+44 20 7946 0958',
    street: '71 Innovation Way',
    city: 'London',
    stateProvince: 'Greater London',
    postalCode: 'WC1N 3AX',
    country: 'United Kingdom',
    qualificationMethod: 'Third-Party Assessment',
    qualificationDocRef: 'QA-3PA-2024-001',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-04-01T08:00:00Z',
  },
];

// ============================================================================
// Form Templates & Instances
// ============================================================================

export const mockFormTemplates: FormTemplate[] = [
  {
    id: 'ft-001',
    documentId: 'doc-006',
    title: 'Cleanroom Entry Log',
    version: '1.0',
    fields: [
      { id: 'f1', name: 'personName', label: 'Person Name', type: 'text', required: true },
      { id: 'f2', name: 'entryDate', label: 'Entry Date', type: 'date', required: true },
      { id: 'f3', name: 'entryTime', label: 'Entry Time', type: 'text', required: true },
      { id: 'f4', name: 'gowningVerified', label: 'Gowning Verified', type: 'checkbox', required: true },
      { id: 'f5', name: 'supervisor', label: 'Supervisor', type: 'text', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved' as const,
    approvedAt: '2024-03-01T08:00:00Z',
    approvedById: 'user-002',
    associatedModule: 'BATCH_RECORD',
    organizationId: 'org-001',
    createdById: 'user-004',
    createdAt: '2024-03-01T08:00:00Z',
  },
  {
    id: 'ft-002',
    documentId: 'doc-004',
    title: 'In-Process Control Record',
    version: '1.0',
    fields: [
      { id: 'f6', name: 'lotNumber', label: 'Lot Number', type: 'text', required: true },
      { id: 'f7', name: 'processStep', label: 'Process Step', type: 'select', required: true, options: ['Weighing', 'Mixing', 'Filling', 'Sterilization', 'Inspection'] },
      { id: 'f8', name: 'parameter', label: 'Parameter', type: 'text', required: true },
      { id: 'f9', name: 'measuredValue', label: 'Measured Value', type: 'number', required: true },
      { id: 'f10', name: 'specification', label: 'Specification', type: 'text', required: true },
      { id: 'f11', name: 'result', label: 'Result', type: 'select', required: true, options: ['Pass', 'Fail', 'N/A'] },
      { id: 'f12', name: 'operatorSignature', label: 'Operator Signature', type: 'signature', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved' as const,
    approvedAt: '2024-02-15T08:00:00Z',
    approvedById: 'user-002',
    associatedModule: 'BATCH_RECORD',
    organizationId: 'org-001',
    createdById: 'user-004',
    createdAt: '2024-02-15T08:00:00Z',
  },
  {
    id: 'ft-003',
    documentId: 'doc-010',
    title: 'CAPA Investigation Form',
    version: '1.2',
    description: 'Root cause analysis and corrective/preventive action form',
    fields: [
      { id: 'fc1', name: 'problemStatement', label: 'Problem Statement', type: 'textarea', required: true },
      { id: 'fc2', name: 'rootCause', label: 'Root Cause', type: 'textarea', required: true },
      { id: 'fc3', name: 'correctiveAction', label: 'Corrective Action', type: 'textarea', required: true },
      { id: 'fc4', name: 'preventiveAction', label: 'Preventive Action', type: 'textarea', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'CAPA',
    organizationId: 'org-001',
    createdById: 'user-001',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'ft-004',
    documentId: 'doc-003',
    title: 'NCR Investigation Form',
    version: '1.0',
    description: 'Non-conformance investigation and disposition form',
    fields: [
      { id: 'fn1', name: 'ncrDescription', label: 'NCR Description', type: 'textarea', required: true },
      { id: 'fn2', name: 'impactAssessment', label: 'Impact Assessment', type: 'textarea', required: true },
      { id: 'fn3', name: 'disposition', label: 'Disposition', type: 'select', required: true, options: ['Use As Is', 'Rework', 'Scrap', 'Return to Supplier'] },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'NCR',
    organizationId: 'org-001',
    createdById: 'user-001',
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'ft-005',
    documentId: 'doc-003',
    title: 'Deviation Report Form',
    version: '1.1',
    description: 'Deviation recording and investigation form',
    fields: [
      { id: 'fd1', name: 'deviationDescription', label: 'Deviation Description', type: 'textarea', required: true },
      { id: 'fd2', name: 'expectedResult', label: 'Expected Result', type: 'text', required: true },
      { id: 'fd3', name: 'actualResult', label: 'Actual Result', type: 'text', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'DEVIATION',
    organizationId: 'org-001',
    createdById: 'user-001',
    createdAt: '2024-02-10T08:00:00Z',
  },
  {
    id: 'ft-006',
    documentId: 'doc-001',
    title: 'Change Control Request Form',
    version: '2.0',
    description: 'Change control initiation and assessment form',
    fields: [
      { id: 'fcc1', name: 'changeDescription', label: 'Change Description', type: 'textarea', required: true },
      { id: 'fcc2', name: 'justification', label: 'Justification', type: 'textarea', required: true },
      { id: 'fcc3', name: 'riskAssessment', label: 'Risk Assessment', type: 'textarea', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'CHANGE_CONTROL',
    organizationId: 'org-001',
    createdById: 'user-001',
    createdAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'ft-007',
    documentId: 'doc-007',
    title: 'Audit Checklist Form',
    version: '1.0',
    description: 'Internal audit checklist and findings form',
    fields: [
      { id: 'fa1', name: 'auditScope', label: 'Audit Scope', type: 'textarea', required: true },
      { id: 'fa2', name: 'findings', label: 'Findings', type: 'textarea', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'AUDIT',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-03-05T08:00:00Z',
  },
  {
    id: 'ft-008',
    documentId: 'doc-010',
    title: 'Risk Assessment Form',
    version: '1.3',
    description: 'ISO 14971 risk assessment form',
    fields: [
      { id: 'fr1', name: 'hazard', label: 'Hazard', type: 'text', required: true },
      { id: 'fr2', name: 'probability', label: 'Probability', type: 'rating', required: true },
      { id: 'fr3', name: 'severity', label: 'Severity', type: 'rating', required: true },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'RISK',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-01-25T08:00:00Z',
  },
  {
    id: 'ft-009',
    documentId: 'doc-001',
    title: 'Training Record Form',
    version: '1.0',
    description: 'Training completion and competency assessment form',
    fields: [
      { id: 'ft1', name: 'traineeName', label: 'Trainee Name', type: 'text', required: true },
      { id: 'ft2', name: 'competencyResult', label: 'Competency Result', type: 'select', required: true, options: ['Competent', 'Not Yet Competent', 'Requires Retraining'] },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'TRAINING',
    organizationId: 'org-001',
    createdById: 'user-003',
    createdAt: '2024-02-20T08:00:00Z',
  },
  {
    id: 'ft-010',
    documentId: 'doc-009',
    title: 'Supplier Qualification Form',
    version: '1.1',
    description: 'Supplier qualification and evaluation form',
    fields: [
      { id: 'fs1', name: 'supplierName', label: 'Supplier Name', type: 'text', required: true },
      { id: 'fs2', name: 'evaluationResult', label: 'Evaluation Result', type: 'select', required: true, options: ['Qualified', 'Conditional', 'Disqualified'] },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'SUPPLIER',
    organizationId: 'org-001',
    createdById: 'user-003',
    createdAt: '2024-03-10T08:00:00Z',
  },
  {
    id: 'ft-011',
    documentId: 'doc-003',
    title: 'OOS/OOT Investigation Form',
    version: '1.0',
    description: 'Out of Specification / Out of Trend investigation form',
    fields: [
      { id: 'fo1', name: 'analyticalMethod', label: 'Analytical Method', type: 'text', required: true },
      { id: 'fo2', name: 'phase1Conclusion', label: 'Phase 1 Conclusion', type: 'select', required: true, options: ['Error Found', 'No Error Found', 'Pending'] },
      { id: 'fo3', name: 'phase2Conclusion', label: 'Phase 2 Conclusion', type: 'select', required: false, options: ['Confirmed OOS', 'Invalidated', 'Pending'] },
    ],
    isActive: true,
    templateStatus: 'Approved',
    associatedModule: 'OOS_OOT',
    organizationId: 'org-001',
    createdById: 'user-004',
    createdAt: '2024-03-15T08:00:00Z',
  },
];

export const mockFormInstances: FormInstance[] = [
  {
    id: 'fi-001',
    templateId: 'ft-001',
    templateVersion: '1.0',
    referenceNumber: 'FORM-2024-001',
    values: { personName: 'Lucas Petit', entryDate: '2024-05-01', entryTime: '07:45', gowningVerified: true, supervisor: 'Marie Dupont' },
    status: 'Approved',
    isLocked: true,
    submittedById: 'user-006',
    submittedAt: '2024-05-01T08:00:00Z',
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2024-05-01T07:45:00Z',
  },
  {
    id: 'fi-003',
    templateId: 'ft-011',
    templateVersion: '1.0',
    referenceNumber: 'FORM-2024-003',
    values: { analyticalMethod: 'HPLC Method QC-M-001', phase1Conclusion: 'No Error Found', phase2Conclusion: 'Confirmed OOS' },
    status: 'Submitted',
    isLocked: false,
    submittedById: 'user-002',
    submittedAt: '2024-04-05T10:00:00Z',
    organizationId: 'org-001',
    createdById: 'user-002',
    createdAt: '2024-04-05T09:30:00Z',
  },
  {
    id: 'fi-002',
    templateId: 'ft-002',
    templateVersion: '1.0',
    referenceNumber: 'FORM-2024-002',
    values: { lotNumber: 'BN-2024-055', processStep: 'Mixing', parameter: 'pH', measuredValue: 7.1, specification: '6.5-7.5', result: 'Pass' },
    status: 'Submitted',
    isLocked: false,
    submittedById: 'user-006',
    submittedAt: '2024-05-01T09:30:00Z',
    organizationId: 'org-001',
    createdById: 'user-006',
    createdAt: '2024-05-01T09:15:00Z',
  },
];

// ============================================================================
// Audits
// ============================================================================

export const mockAudits: Audit[] = [
  {
    id: 'audit-001',
    auditNumber: 'AUD-2024-001',
    title: 'Q1 2024 Internal Quality Audit',
    type: 'Internal',
    status: 'Completed',
    scope: 'Document control and batch record review process',
    scheduledDate: '2024-04-01T08:00:00Z',
    completedDate: '2024-04-03T17:00:00Z',
    leadAuditor: 'Sophie Laurent',
    auditees: ['Pierre Bernard', 'Lucas Petit', 'Jean Martin'],
    findings: [
      { id: 'af-001', description: 'Missing QA review signatures on batch records', severity: 'Major', referenceClause: 'ISO 13485:2016 §4.2.4', correctiveActionRequired: true, capaId: 'capa-002' },
      { id: 'af-002', description: 'Document review cycle not consistently tracked', severity: 'Minor', referenceClause: 'ISO 13485:2016 §4.2.3', correctiveActionRequired: true },
      { id: 'af-003', description: 'Good documentation practices observed in production', severity: 'Observation', correctiveActionRequired: false },
    ],
    organizationId: 'org-001',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-04-03T17:00:00Z',
  },
  {
    id: 'audit-002',
    auditNumber: 'AUD-2024-002',
    title: 'Supplier Audit - MedPharm Raw Materials',
    type: 'Supplier',
    status: 'Planned',
    scope: 'Supplier quality system and raw material control',
    scheduledDate: '2024-07-15T08:00:00Z',
    leadAuditor: 'Sophie Laurent',
    auditees: ['MedPharm Quality Team'],
    organizationId: 'org-001',
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z',
  },
  {
    id: 'audit-003',
    auditNumber: 'AUD-2024-003',
    title: 'Q2 2024 Internal Quality Audit',
    type: 'Internal',
    status: 'In Progress',
    scope: 'CAPA effectiveness and training compliance',
    scheduledDate: '2024-06-10T08:00:00Z',
    leadAuditor: 'Sophie Laurent',
    auditees: ['Jean Martin', 'Marie Dupont'],
    organizationId: 'org-001',
    createdAt: '2024-05-15T08:00:00Z',
    updatedAt: '2024-06-10T08:00:00Z',
  },
];

// ============================================================================
// Training
// ============================================================================

export const mockTraining: Training[] = [
  {
    id: 'train-001',
    title: 'SOP-QMS-001 Document Control Training',
    description: 'Training on the updated document control procedure v3.0',
    type: 'SOP',
    status: 'Completed',
    assignedTo: 'user-006',
    dueDate: '2024-02-15T00:00:00Z',
    completedDate: '2024-02-10T10:00:00Z',
    documentId: 'doc-001',
    organizationId: 'org-001',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-02-10T10:00:00Z',
  },
  {
    id: 'train-002',
    title: 'Cleanroom Gowning Certification',
    description: 'Annual recertification for cleanroom gowning procedure',
    type: 'Certification',
    status: 'Overdue',
    assignedTo: 'user-006',
    dueDate: '2024-04-01T00:00:00Z',
    documentId: 'doc-006',
    organizationId: 'org-001',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-04-01T08:00:00Z',
  },
  {
    id: 'train-003',
    title: 'ISO 13485:2016 Regulatory Update',
    description: 'Training on recent regulatory updates and their impact',
    type: 'Regulatory',
    status: 'Planned',
    assignedTo: 'user-002',
    dueDate: '2024-07-15T00:00:00Z',
    organizationId: 'org-001',
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-01T08:00:00Z',
  },
  {
    id: 'train-004',
    title: 'New Employee Onboarding - Quality System',
    description: 'Comprehensive onboarding training for the QMS',
    type: 'Onboarding',
    status: 'In Progress',
    assignedTo: 'user-006',
    dueDate: '2024-06-30T00:00:00Z',
    organizationId: 'org-001',
    createdAt: '2024-05-15T08:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'train-005',
    title: 'Internal Auditor Training',
    description: 'Training on internal audit methodology and ISO 13485 requirements',
    type: 'Skill',
    status: 'Completed',
    assignedTo: 'user-003',
    dueDate: '2024-03-01T00:00:00Z',
    completedDate: '2024-02-28T10:00:00Z',
    organizationId: 'org-001',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-02-28T10:00:00Z',
  },
];

// ============================================================================
// Risks
// ============================================================================

export const mockRisks: Risk[] = [
  {
    id: 'risk-001',
    riskNumber: 'RISK-2024-001',
    title: 'HEPA Filter Failure in Grade A',
    category: 'Process',
    probability: 2,
    impact: 5,
    detectability: 3,
    rpn: 30,
    riskLevel: 'High',
    mitigation: 'Implement predictive maintenance for HEPA filters. Add differential pressure monitoring with alerts.',
    residualRisk: 'Low - with predictive maintenance and monitoring in place',
    residualProbability: 1,
    residualImpact: 4,
    residualDetectability: 2,
    status: 'Mitigated',
    organizationId: 'org-001',
    createdAt: '2024-03-16T08:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'risk-002',
    riskNumber: 'RISK-2024-002',
    title: 'Supply Chain Disruption - API X-200',
    category: 'Supplier',
    probability: 3,
    impact: 4,
    detectability: 4,
    rpn: 48,
    riskLevel: 'High',
    mitigation: 'Qualify second source supplier. Maintain 3-month safety stock.',
    residualRisk: 'Medium - dependent on second source qualification timeline',
    residualProbability: 2,
    residualImpact: 3,
    residualDetectability: 3,
    linkedCapaId: 'capa-004',
    linkedCapaIds: ['capa-004'],
    status: 'Open',
    organizationId: 'org-001',
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-04-01T08:00:00Z',
  },
  {
    id: 'risk-003',
    riskNumber: 'RISK-2024-003',
    title: 'Labeling Error on Finished Product',
    category: 'Product',
    probability: 2,
    impact: 4,
    detectability: 2,
    rpn: 16,
    riskLevel: 'Medium',
    mitigation: 'Implement label verification step with barcode scanning.',
    residualProbability: 1,
    residualImpact: 3,
    residualDetectability: 1,
    status: 'Mitigated',
    organizationId: 'org-001',
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'risk-004',
    riskNumber: 'RISK-2024-004',
    title: 'Data Integrity - Batch Record System',
    category: 'System',
    probability: 1,
    impact: 5,
    detectability: 2,
    rpn: 10,
    riskLevel: 'Low',
    mitigation: 'Implement electronic signatures with audit trail. Regular data integrity reviews.',
    status: 'Accepted',
    organizationId: 'org-001',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
  },
];

// ============================================================================
// Audit Trails
// ============================================================================

export const mockAuditTrails: AuditTrail[] = [
  { id: 'at-001', action: 'APPROVE', tableName: 'Document', recordId: 'doc-001', userId: 'user-004', userEmail: 'dc@qms-demo.com', newValues: { status: 'Approved', version: '3.0' }, organizationId: 'org-001', createdAt: '2024-01-15T10:00:00Z' },
  { id: 'at-002', action: 'CREATE', tableName: 'Capa', recordId: 'capa-001', userId: 'user-002', userEmail: 'qm@qms-demo.com', newValues: { capaNumber: 'CAPA-2024-001', status: 'Open' }, organizationId: 'org-001', createdAt: '2024-03-16T08:00:00Z' },
  { id: 'at-003', action: 'UPDATE', tableName: 'Capa', recordId: 'capa-001', userId: 'user-002', userEmail: 'qm@qms-demo.com', oldValues: { status: 'Open' }, newValues: { status: 'Investigation' }, organizationId: 'org-001', createdAt: '2024-03-20T10:00:00Z' },
  { id: 'at-004', action: 'CREATE', tableName: 'NonConformance', recordId: 'ncr-002', userId: 'user-002', userEmail: 'qm@qms-demo.com', newValues: { ncrNumber: 'NCR-2024-002', type: 'OOS' }, organizationId: 'org-001', createdAt: '2024-04-05T08:00:00Z' },
  { id: 'at-005', action: 'SIGN', tableName: 'BatchRecord', recordId: 'batch-002', userId: 'user-002', userEmail: 'qm@qms-demo.com', newValues: { status: 'Released', qaReleaseDate: '2024-04-20T14:00:00Z' }, organizationId: 'org-001', createdAt: '2024-04-20T14:00:00Z' },
  { id: 'at-006', action: 'UPDATE', tableName: 'Document', recordId: 'doc-006', userId: 'user-004', userEmail: 'dc@qms-demo.com', oldValues: { status: 'Approved' }, newValues: { status: 'Under Review' }, organizationId: 'org-001', createdAt: '2024-05-15T10:00:00Z' },
  { id: 'at-007', action: 'CREATE', tableName: 'BatchRecord', recordId: 'batch-001', userId: 'user-006', userEmail: 'operator@qms-demo.com', newValues: { lotNumber: 'BN-2024-055', status: 'In Progress' }, organizationId: 'org-001', createdAt: '2024-05-01T08:00:00Z' },
  { id: 'at-008', action: 'LOGIN', tableName: 'Profile', recordId: 'user-001', userId: 'user-001', userEmail: 'admin@qms-demo.com', organizationId: 'org-001', createdAt: '2024-06-01T08:00:00Z' },
];

// ============================================================================
// Document Prerequisites
// ============================================================================

export const mockPrerequisites: DocumentPrerequisite[] = [
  { id: 'prereq-001', organizationId: 'org-001', recordType: 'CAPA', requiredDocType: 'SOP', requiredDocRef: 'SOP-QMS-002', isMandatory: true, description: 'CAPA Management SOP must be approved before creating CAPA records', createdAt: '2024-01-15T08:00:00Z' },
  { id: 'prereq-002', organizationId: 'org-001', recordType: 'NCR', requiredDocType: 'SOP', requiredDocRef: 'SOP-QMS-003', isMandatory: true, description: 'Non-Conformance Management SOP must be approved before creating NCR records', createdAt: '2024-01-15T08:00:00Z' },
  { id: 'prereq-003', organizationId: 'org-001', recordType: 'AUDIT', requiredDocType: 'SOP', requiredDocRef: 'SOP-QMS-004', isMandatory: true, description: 'Internal Audit Procedure must be approved before scheduling audits', createdAt: '2024-01-15T08:00:00Z' },
  { id: 'prereq-004', organizationId: 'org-001', recordType: 'CHANGE_CONTROL', requiredDocType: 'SOP', isMandatory: true, description: 'Change Control SOP must be in place', createdAt: '2024-01-15T08:00:00Z' },
  { id: 'prereq-005', organizationId: 'org-001', recordType: 'DEVIATION', requiredDocType: 'SOP', isMandatory: false, description: 'Deviation handling SOP recommended', createdAt: '2024-01-15T08:00:00Z' },
];

// ============================================================================
// Change Controls
// ============================================================================

export const mockChangeControls: ChangeControl[] = [
  {
    id: 'cc-001',
    ccNumber: 'CC-2024-001',
    title: 'HEPA Filter Replacement - Grade A Cleanroom',
    type: 'Planned',
    status: 'In Implementation',
    priority: 'Critical',
    category: 'Equipment',
    description: 'Replacement of primary HEPA filter in Grade A cleanroom after degradation detected during environmental monitoring.',
    justification: 'HEPA filter degradation identified via environmental monitoring excursion. Filter has reached end of service life per manufacturer specifications.',
    proposedChange: 'Replace existing HEPA filter with new equivalent unit (Model: Camfil Megalam SP). Update PM schedule to reflect new filter life assessment.',
    riskAssessment: 'Risk of continued environmental excursions if filter not replaced. Installation will require temporary cleanroom shutdown - planned for weekend maintenance window.',
    impactAnalysis: 'Impact on production schedule minimal - planned during weekend downtime. No impact on product quality as cleanroom will be re-qualified before production resumes.',
    implementationPlan: '1) Order replacement filter, 2) Schedule weekend installation, 3) Perform DQ/IQ/OQ, 4) Re-qualify cleanroom, 5) Update PM schedule',
    implementationDate: '2024-04-20T08:00:00Z',
    linkedCapaId: 'capa-001',
    linkedDocumentId: 'doc-004',
    assignedTo: 'user-002',
    requestedBy: 'user-001',
    approvedBy: 'user-005',
    dueDate: '2024-05-15T00:00:00Z',
    createdById: 'user-001',
    organizationId: 'org-001',
    createdAt: '2024-03-20T08:00:00Z',
    updatedAt: '2024-04-20T10:00:00Z',
  },
  {
    id: 'cc-002',
    ccNumber: 'CC-2024-002',
    title: 'Label Template Update - Device Alpha',
    type: 'Planned',
    status: 'Completed',
    priority: 'High',
    category: 'Document',
    description: 'Update label template for Device Alpha to reflect new shelf-life of 24 months (previously 36 months).',
    justification: 'Stability data supports 24-month shelf life. Label template in printing system contained incorrect expiry date format.',
    proposedChange: 'Update label template in printing system. Modify barcode to include new expiry date format. Add verification step in label approval process.',
    riskAssessment: 'Low risk - change limited to labeling. Risk of using old templates mitigated by system lockout of obsolete templates.',
    impactAnalysis: 'No impact on product quality. Change affects only labeling. All future batches will use updated template.',
    implementationPlan: '1) Update template in printing system, 2) Validate new template, 3) Obsolete old template, 4) Train labeling operators',
    implementationDate: '2024-03-01T08:00:00Z',
    completionDate: '2024-03-15T16:00:00Z',
    linkedCapaId: 'capa-005',
    assignedTo: 'user-004',
    requestedBy: 'user-001',
    approvedBy: 'user-002',
    dueDate: '2024-03-31T00:00:00Z',
    createdById: 'user-001',
    organizationId: 'org-001',
    createdAt: '2024-02-25T08:00:00Z',
    updatedAt: '2024-03-15T16:00:00Z',
  },
  {
    id: 'cc-003',
    ccNumber: 'CC-2024-003',
    title: 'Manufacturing Process Parameter Change - Mixing Speed',
    type: 'Planned',
    status: 'Under Review',
    priority: 'Medium',
    category: 'Process',
    description: 'Proposed change to mixing speed from 200 RPM to 220 RPM based on process optimization study.',
    justification: 'Process development study shows improved homogeneity at 220 RPM without affecting product quality attributes.',
    proposedChange: 'Increase mixing speed from 200 RPM to 220 RPM in manufacturing SOP and batch record template.',
    riskAssessment: 'Medium risk - requires re-validation of mixing step. Impact on downstream processing needs assessment.',
    impactAnalysis: 'May affect mixing time, temperature profile, and subsequent filling operations. Requires updated validation.',
    assignedTo: 'user-002',
    requestedBy: 'user-006',
    dueDate: '2024-08-01T00:00:00Z',
    createdById: 'user-006',
    organizationId: 'org-001',
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2024-05-15T10:00:00Z',
  },
  {
    id: 'cc-004',
    ccNumber: 'CC-2024-004',
    title: 'Emergency: HVAC System Bypass Protocol',
    type: 'Emergency',
    status: 'Approved',
    priority: 'Critical',
    category: 'Facility',
    description: 'Emergency change to implement HVAC bypass protocol during chiller replacement.',
    justification: 'Chiller unit failure requires immediate replacement. HVAC bypass needed to maintain partial cleanroom functionality during 48-hour replacement window.',
    proposedChange: 'Implement temporary HVAC bypass with enhanced environmental monitoring. Reduce cleanroom operations to essential activities only.',
    riskAssessment: 'High risk during bypass period. Enhanced monitoring and restricted operations mitigate risk to acceptable level.',
    impactAnalysis: 'Production limited to critical operations for 48 hours. All Grade B/C areas maintained. Grade A area restricted.',
    implementationPlan: '1) Install temporary monitoring, 2) Activate bypass protocol, 3) Replace chiller, 4) Restore normal operations, 5) Re-qualify',
    assignedTo: 'user-001',
    requestedBy: 'user-001',
    approvedBy: 'user-005',
    dueDate: '2024-05-20T00:00:00Z',
    createdById: 'user-001',
    organizationId: 'org-001',
    createdAt: '2024-05-10T06:00:00Z',
    updatedAt: '2024-05-10T12:00:00Z',
  },
];

// ============================================================================
// Deviations
// ============================================================================

export const mockDeviations: Deviation[] = [
  {
    id: 'dev-001',
    devNumber: 'DEV-2024-001',
    title: 'Temperature Excursion During Product Storage',
    type: 'Unplanned',
    status: 'Under Investigation',
    severity: 'Major',
    category: 'Environment',
    description: 'Cold storage unit temperature exceeded 2-8°C range for 3 hours during compressor malfunction.',
    deviationDetails: 'Temperature monitoring system recorded temperatures up to 12°C in cold storage unit CS-003 between 02:00 and 05:00 on 2024-04-15. Compressor malfunction identified as root cause. Affected products: Sterile Solution Alpha Lot BN-2024-052 (500 vials), Sterile Solution Beta Lot BN-2024-042 (1000 vials).',
    riskAssessment: 'Preliminary risk assessment indicates potential impact on product stability. Stability data for short-term temperature excursions up to 25°C for 24 hours available for Sterile Solution Alpha.',
    lotNumber: 'BN-2024-052',
    productCode: 'PROD-ALPHA-001',
    quantityAffected: 500,
    linkedCapaId: 'capa-002',
    assignedTo: 'user-002',
    dueDate: '2024-05-15T00:00:00Z',
    createdById: 'user-006',
    organizationId: 'org-001',
    createdAt: '2024-04-15T06:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'dev-002',
    devNumber: 'DEV-2024-002',
    title: 'Incorrect Weight of API in Batch BN-2024-055',
    type: 'Unplanned',
    status: 'Pending QA Review',
    severity: 'Minor',
    category: 'Process',
    description: 'API weighing step completed with weight outside normal range but within specification limits.',
    deviationDetails: 'API X-200 weighed at 251.2 kg vs target of 250.0 kg. This is within the acceptable range of 250.0 ± 2.5 kg (SOP-PROD-001). However, the deviation from target exceeds the normal operating range of ± 1.0 kg.',
    justification: 'Weighing within specification but outside normal operating range. Scale calibration verified as current.',
    riskAssessment: 'Low risk - final weight within specification. No impact on product quality expected.',
    correctiveAction: 'Retrain operator on target weight practices. Review scale calibration frequency.',
    lotNumber: 'BN-2024-055',
    productCode: 'PROD-ALPHA-001',
    quantityAffected: 1,
    linkedDocumentId: 'doc-004',
    assignedTo: 'user-002',
    dueDate: '2024-06-01T00:00:00Z',
    createdById: 'user-006',
    organizationId: 'org-001',
    createdAt: '2024-05-01T09:00:00Z',
    updatedAt: '2024-05-10T10:00:00Z',
  },
  {
    id: 'dev-003',
    devNumber: 'DEV-2024-003',
    title: 'Planned Deviation - Alternative Supplier for Packaging Material',
    type: 'Planned',
    status: 'Approved',
    severity: 'Minor',
    category: 'Material',
    description: 'Temporary use of alternative packaging supplier for blister packs while primary supplier resolves quality issue.',
    deviationDetails: 'Primary packaging supplier PharmaPack Solutions SA reported a quality issue with their blister film production. Alternative supplier PackSafe Industries qualified for temporary supply of Class I blister packaging material.',
    justification: 'Primary supplier quality issue on blister film. Alternative supplier qualified per SOP-QMS-005. Temporary deviation for 3 months or until primary supplier resolves issue.',
    riskAssessment: 'Low risk - alternative supplier qualified and material specifications verified identical. No impact on product protection or stability.',
    correctiveAction: 'Monitor primary supplier quality issue resolution. Revert to primary supplier upon qualification.',
    preventiveAction: 'Maintain approved alternative supplier list for critical packaging materials.',
    linkedDocumentId: 'doc-009',
    assignedTo: 'user-002',
    dueDate: '2024-07-15T00:00:00Z',
    closedDate: '2024-06-30T10:00:00Z',
    createdById: 'user-002',
    organizationId: 'org-001',
    createdAt: '2024-04-20T08:00:00Z',
    updatedAt: '2024-06-30T10:00:00Z',
  },
  {
    id: 'dev-004',
    devNumber: 'DEV-2024-004',
    title: 'Operator Not Following Gowning Procedure',
    type: 'Unplanned',
    status: 'Open',
    severity: 'Major',
    category: 'Personnel',
    description: 'Operator observed not following proper gowning sequence when entering Grade C area.',
    deviationDetails: 'During routine supervision, operator Lucas Petit was observed entering Grade C area without completing the full gowning sequence specified in WI-PROD-001. Missing step: hand sanitization after donning gloves.',
    lotNumber: 'BN-2024-055',
    assignedTo: 'user-002',
    dueDate: '2024-06-15T00:00:00Z',
    createdById: 'user-003',
    organizationId: 'org-001',
    createdAt: '2024-05-20T14:00:00Z',
    updatedAt: '2024-05-20T14:00:00Z',
  },
];
